### PR TITLE
internship list updated

### PR DESCRIPTION
**Pull request by charu1603**
please assign hactoberfest label

### CODE REVIEW

**Comment by avinash201199** [comment]
please remove from readme file

**Comment by charu1603** [comment]
I have just clicked on the delete file option in the readme file edit section.  is that I have to do?

**Comment by charu1603** [comment]
This is my first contribution sir . please guide me

**Comment by avinash201199** [comment]
make pr again

**Comment by avinash201199** [comment]
if you have any doubts then contact me on linkedin

**Pull request closed without merging**
