### PR TITLE
created website

### PR DESCRIPTION
**Pull request by 17Moons**
So , there are few things:
1. Put all md in folder with names with no spaces only underscores
2. All md files name should not have spaces
3. Css will be added later on 
4. I will automate the website soon 
5. Thank you

### CODE REVIEW

**Comment by avinash201199** [comment]
having so many html pages won't help ,you can add all in single page , accepting pr only see the changes , will revert if it's not match the requirement

**Comment by avinash201199** [comment]
hey it's uncomplete website , reverting the change

**Comment by 17Moons** [comment]
If you ommit the spaces in readme.md of all profiles then it can be a complete website. But did you really expect a whole website in a single commit ?

**Comment by 17Moons** [comment]
> having so many html pages won't help ,you can add all in single page , accepting pr only see the changes , will revert if it's not match the requirement

makes sense

**Comment by avinash201199** [comment]
> If you ommit the spaces in readme.md of all profiles then it can be a complete website. But did you really expect a whole website in a single commit ?

not in one commit but atleast a structure of the website for example look this - https://free-courses-with-certificates.netlify.app/   (https://github.com/avinash201199/Free-courses-with-Certificates)
it was added in a single commit. 

You have added only html portion , no styling and no functionality , ish tarah se tumhe bahut jada pr banane padte website ko complete karne ke liye and important thing is that,  2,3 pr se jada ek repo mein contribute karna recommend nhi hai because vo log har pr ko review karte hai , agar bahut jada pr ek hi repo mein dekh liya tto blacklist kar sakte hai repository ko

**Comment by avinash201199** [comment]
I appreciate your effort , you can make the complete website in your local systems once it done then you can make a pr , I will accept it .

**Comment by avinash201199** [comment]
for example you can take code from here https://github.com/avinash201199/Competitions-and-Programs-List

**Comment by 17Moons** [comment]
> > If you ommit the spaces in readme.md of all profiles then it can be a complete website. But did you really expect a whole website in a single commit ?
> 
> not in one commit but atleast a structure of the website for example look this - https://free-courses-with-certificates.netlify.app/ (https://github.com/avinash201199/Free-courses-with-Certificates) it was added in a single commit.
> 
> You have added only html portion , no styling and no functionality , ish tarah se tumhe bahut jada pr banane padte website ko complete karne ke liye and important thing is that, 2,3 pr se jada ek repo mein contribute karna recommend nhi hai because vo log har pr ko review karte hai , agar bahut jada pr ek hi repo mein dekh liya tto blacklist kar sakte hai repository ko

oh ye pata nhi that mujhe thanks

**Comment by 17Moons** [comment]
> > > If you ommit the spaces in readme.md of all profiles then it can be a complete website. But did you really expect a whole website in a single commit ?
> > 
> > 
> > not in one commit but atleast a structure of the website for example look this - https://free-courses-with-certificates.netlify.app/ (https://github.com/avinash201199/Free-courses-with-Certificates) it was added in a single commit.
> > You have added only html portion , no styling and no functionality , ish tarah se tumhe bahut jada pr banane padte website ko complete karne ke liye and important thing is that, 2,3 pr se jada ek repo mein contribute karna recommend nhi hai because vo log har pr ko review karte hai , agar bahut jada pr ek hi repo mein dekh liya tto blacklist kar sakte hai repository ko
> 
> oh ye pata nhi tha mujhe thanks

**Comment by avinash201199** [comment]
> > > > If you ommit the spaces in readme.md of all profiles then it can be a complete website. But did you really expect a whole website in a single commit ?
> > > 
> > > 
> > > not in one commit but atleast a structure of the website for example look this - https://free-courses-with-certificates.netlify.app/ (https://github.com/avinash201199/Free-courses-with-Certificates) it was added in a single commit.
> > > You have added only html portion , no styling and no functionality , ish tarah se tumhe bahut jada pr banane padte website ko complete karne ke liye and important thing is that, 2,3 pr se jada ek repo mein contribute karna recommend nhi hai because vo log har pr ko review karte hai , agar bahut jada pr ek hi repo mein dekh liya tto blacklist kar sakte hai repository ko
> > 
> > 
> > oh ye pata nhi tha mujhe thanks

it's okay you can contribute in other repo's as well 

List of some Github Repositories to contribute in Hacktoberfest

1- https://github.com/avinash201199/Competitions-and-Programs-List
2- https://github.com/avinash201199/Free-courses-with-Certificates
3- https://github.com/avinash201199/Paid-Internship-List
4- https://github.com/avinash201199/weather-app
5- https://github.com/avinash201199/stopwatch
6- https://github.com/avinash201199/To-Do-List
7- https://github.com/avinash201199/Portfolio-Collection

**Comment by 17Moons** [comment]
thanks you very much

**Pull request merged**
